Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -25,57 +25,6 @@ jobs:
     
     - name: Clonar st7789
       run: git clone https://github.com/russhughes/st7789_mpy.git
-
-    
-    #- name: Copy tdt_config and some fonts like frozen modules
-     # run: |
-      # cp "$GITHUB_WORKSPACE/s3lcd/examples/configs/t-display-s3/tft_config.py" "$GITHUB_WORKSPACE/s3lcd/modules/"
-       #cp "$GITHUB_WORKSPACE/s3lcd/examples/configs/t-display-s3/tft_buttons.py" "$GITHUB_WORKSPACE/s3lcd/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/examples/chango/chango_16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/examples/chango/chango_32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/examples/chango/chango_64.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/astrol.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/gotheng.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/greekc.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/italict.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/lowmat.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/marker.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/music.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/romancs.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga1_8x8.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga1_8x16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga1_16x16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga1_16x32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga1_bold_16x16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga1_bold_16x32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/truetype/NotoSerif_32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/examples/chango/chango.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/truetype/NotoSans_32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/truetype/NotoSansMono_32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga2_8x8.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga2_8x16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga2_16x16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga2_16x32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga2_bold_16x16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/bitmap/vga2_bold_16x32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/cyrilc.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/gothger.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/gothita.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/greekcs.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/greekp.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/greeks.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/italcc.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/italiccs.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/meteo.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/romanc.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/romand.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/romanp.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/romans.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/romant.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/scriptc.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/scripts.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/symbol.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
-      # cp $GITHUB_WORKSPACE/s3lcd/fonts/vector/uppmat.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       
     - name: Instalar dependencias
       run: |
@@ -94,7 +43,7 @@ jobs:
         cd
         
     - name: Compile with St7789
-      continue-on-error: true
+     # continue-on-error: true
       run: |
         source esp/esp-idf/export.sh
         cd micropython/
@@ -104,7 +53,7 @@ jobs:
         cp ${GITHUB_WORKSPACE}/st7789_mpy/fonts/bitmap/vga1_16x16.py modules
         cp ${GITHUB_WORKSPACE}/st7789_mpy/fonts/truetype/NotoSans_32.py modules
         cp ${GITHUB_WORKSPACE}/st7789_mpy/fonts/vector/scripts.py modules
-        idf.py \
+        idf.py --list-targets \
           -D MICROPY_BOARD=ESP32_GENERIC \
           -D MICROPY_BOARD_DIR="$GITHUB_WORKSPACE/micropython/ports/esp32/boards/" \
           -D USER_C_MODULES="$GITHUB_WORKSPACE/micropython.cmake" \
@@ -113,12 +62,12 @@ jobs:
       # -D MICROPY_FROZEN_MANIFEST="" \
     
     - name: Move binaries with S3LCD + SmartConfig
-      if: success() || failure()
+     # if: success() || failure()
       run: |
         mkdir -p ./artifacts
-        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/micropython.bin ./artifacts/micropython.bin || true
-        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/bootloader/bootloader.bin ./artifacts/bootloader.bin || true
-        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/partition_table/partition-table.bin ./artifacts/partition-table.bin || true
+        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/micropython.bin ./artifacts/
+        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/bootloader/bootloader.bin ./artifacts/
+        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/partition_table/partition-table.bin ./artifacts/
     
     - name: Generate Tag
       id: tag
